# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# theme: jekyll-theme-so-simple
# remote_theme: mmistakes/so-simple-theme
skin: "/assets/css/skins/dark.css"
locale: en-US
title: "Ryan DowlingSoka"
description: "Technical Art Supervisor @ Bioware"
baseurl: # the subpath of your site, e.g. "/blog"
url: "https://ryandowlingsoka.com" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
logo: # path of site logo, e.g. "/images/logo.png"
date_format: "%B %-d, %Y"
read_time: # reading time estimates, e.g. true
words_per_minute: # 200
mathjax:
  enable: # MathJax equations, e.g. true, false (default)
  combo:  # "tex-svg" (default), "tex-mml-chtml", etc.: docs.mathjax.org/en/latest/web/components/combined.html
  tags:  # "none", "ams" (default), "all"
#google_fonts:
#  - name: "Source Sans Pro"
#    weights: "400,400i,700,700i"
#  - name: "Lora"
#    weights: "400,400i,700,700i"
google_analytics: G-W0NEXY7DC4
disqus:
  shortname: # Disqus shortname, e.g. "my_disqus_shortname"
twitter:
  username: RyanDowlingSoka # site's Twitter username, e.g. "mmistakes"
# url: "https://ryandowlingsoka.com"

# Liquid
liquid:
  error_mode: strict

# Build settings
permalink: /:categories/:title/
markdown: kramdown
feed:
  path: atom.xml

sass:
  style: compressed

# Pagination - https://jekyllrb.com/docs/pagination/
# paginate: 10
# paginate_path: /page:num/

# Search
search_full_content: true # can have performance implications for large sites

# Taxonomy pages
# category_archive_path: "/categories/#"
# tag_archive_path: "/tags/#"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

collections:
  unreal:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll_picture_tag
  - jekyll-redirect-from

# Front Matter Defaults
defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/test_twitter_card.webp
  # Posts defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      share: true
  # Unreal defaults
  - scope:
      path: "_unreal"
      type: unreal
    values:
      layout: page
  # Portfolio defaults
  - scope:
      path: "_portfolio"
      type: portfolio
    values:
      layout: page

# Site Author
author:
  name: Ryan DowlingSoka
  picture: 
  email: ryan@dowlingsoka.com
  twitter: RyanDowlingSoka
  links:
    - title:
      url:
      icon:

# Footer Links
footer_links:
  - title: Feed
    url: atom.xml
    icon: rss
  - title: Twitter
    url: https://twitter.com/RyanDowlingSoka
    icon: twitter-square
  - title: Linked.In
    url: https://www.linkedin.com/in/ryandowlingsoka/
    icon: linkedin-square
  - title: GitHub
    url: https://github.com/RyanDowlingSoka
    icon: github-square
  - title: gamedev.place
    url: https://mastodon.gamedev.place/@ryan_dowlingsoka
    icon: mastodon-square

picture:
  ignore_missing_images: true
